steps:
- checkout: self
  fetchDepth: 2

- template: show-environment-variables.yml
- template: show-disk-usage.yml

- bash: |
    sudo apt install gdb

    export PATH=$PATH:$HOME/.local/bin:$HOME/Library/Python/2.7/bin/:$HOME
    echo "##vso[task.prependpath]$HOME/.local/bin"
    echo "##vso[task.prependpath]$HOME/Library/Python/2.7/bin"
    echo "##vso[task.prependpath]$HOME"

    mkdir -p $HOME/rustsrc
  displayName:  Prep

- bash: |
    export RUN_SCRIPT="$BUILD_SOURCESDIRECTORY/src/ci/init_repo.sh . $HOME/rustsrc && src/ci/docker/run.sh $IMAGE"
    echo "##vso[task.setvariable variable=IMAGE]$IMAGE"
    echo "##vso[task.setvariable variable=RUN_SCRIPT]$RUN_SCRIPT"
  displayName: Prepare run script

- template: show-environment-variables.yml

- bash: sudo sh -c 'echo "/checkout/obj/cores/core.%p.%E" > /proc/sys/kernel/core_pattern'
  displayName: Enable core dump

- template: verify-publish-toolstate.yml

- template: run-script.yml
