steps:
# Log time information from this machine and an external machine for insight into possible
# clock drift. Timezones don't matter since relative deltas give all the necessary info.
- bash: |
    date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
  displayName: Log time information (before)

- bash: |
    which sccache
    stamp sh -x -c "$RUN_SCRIPT"
  env:
    CI: true
    CI_JOB_NAME: $(IMAGE)
    SRC: .

    # Explicitly decrypt secret variables
    # See https://docs.microsoft.com/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables
    AWS_ACCESS_KEY_ID: $(SCCACHE_AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(SCCACHE_AWS_SECRET_ACCESS_KEY)
  displayName: Run script

- bash: |
    date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
  displayName: Log time information (after)
