[package]
authors = ["The Rust Project Developers"]
name = "rustc_metadata_utils"
version = "0.0.0"

[lib]
name = "rustc_metadata_utils"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
rustc = { path = "../librustc" }
syntax_pos = { path = "../libsyntax_pos" }
