sudo: false
language: rust
cache: cargo

os:
  - linux
  - osx

rust:
  - nightly

script:
  - rustup component add rust-src
  - cargo install xargo || echo "Skipping xargo install"
  - cargo install hyperfine || echo "Skipping hyperfine install"
  - ./prepare_libcore.sh
  - ./build.sh

env:
  - RUST_BACKTRACE=1
