language: rust
rust:
- nightly
before_script:
- export PATH=$HOME/.local/bin:$PATH
- rustup target add i686-unknown-linux-gnu
- rustup target add i686-pc-windows-gnu
- rustup target add i686-pc-windows-msvc
script:
- |
  export RUST_SYSROOT=$HOME/rust &&
  cargo build &&
  cargo test &&
  cargo install &&
  cd cargo-miri-test &&
  cargo miri &&
  cargo miri test &&
  cd ..
notifications:
  email:
    on_success: never
env:
  global:
  - RUST_TEST_NOCAPTURE=1
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
