sudo: false
language: rust
cache: cargo

rust:
  - nightly

script:
  - rustup component add rust-src
  - cargo install xargo || echo "Skipping xargo install"
  - ./prepare_libcore.sh
  - ./build.sh

env:
  - RUST_BACKTRACE=1
