language: rust
cache:
  directories:
    - $HOME/.cargo

os:
  - linux
  - osx

rust:
  - nightly

script:
  - ./prepare.sh
  - ./test.sh --release

env:
  global:
    # Enable backtraces for easier debugging.
    - RUST_BACKTRACE=1
    # Reduce amount of benchmark runs as they are slow.
    - COMPILE_RUNS=2 RUN_RUNS=2
