language: rust
rust:
- nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
- rustup target add i686-unknown-linux-gnu
- rustup target add i686-pc-windows-gnu
- rustup target add i686-pc-windows-msvc
script:
- |
  env RUST_SYSROOT=$HOME/rust travis-cargo build &&
  env RUST_SYSROOT=$HOME/rust travis-cargo test
notifications:
  email:
    on_success: never
env:
  global:
  - RUST_TEST_NOCAPTURE=1
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
