language: rust
rust:
- nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
- sh ~/rust-installer/rustup.sh --add-target=i686-unknown-linux-gnu --prefix=/home/travis/rust -y --disable-sudo
- sh ~/rust-installer/rustup.sh --add-target=i686-pc-windows-gnu --prefix=/home/travis/rust -y --disable-sudo
- sh ~/rust-installer/rustup.sh --add-target=i686-pc-windows-msvc --prefix=/home/travis/rust -y --disable-sudo
script:
- |
  env RUST_SYSROOT=$HOME/rust travis-cargo build &&
  env RUST_SYSROOT=$HOME/rust travis-cargo test &&
  env RUST_SYSROOT=$HOME/rust travis-cargo install &&
  cd cargo-miri-test &&
  env RUST_SYSROOT=$HOME/rust travis-cargo miri &&
  env RUST_SYSROOT=$HOME/rust travis-cargo miri test &&
  cd ..
notifications:
  email:
    on_success: never
env:
  global:
  - RUST_TEST_NOCAPTURE=1
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
