environment:
    global:
        PROJECT_NAME: rust-clippy
    matrix:
        #- TARGET: i686-pc-windows-gnu
        #- TARGET: i686-pc-windows-msvc
        #- TARGET: x86_64-pc-windows-gnu
        - TARGET: x86_64-pc-windows-msvc

branches:
    # Only build AppVeyor on r+ and try branch
    only:
      - auto
      - try

cache:
    - '%USERPROFILE%\.cargo'
on_finish:
    - cargo install -Z install-upgrade cargo-cache --debug
    - cargo cache --autoclean

install:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - rustup-init.exe -y --default-host %TARGET% --default-toolchain nightly --profile=minimal
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - del rust-toolchain
    - cargo install -Z install-upgrade rustup-toolchain-install-master --debug || echo "rustup-toolchain-install-master already installed"
    - rustup-toolchain-install-master -f -n master
    - rustup component add rustfmt --toolchain nightly & exit 0 # Format test handles missing rustfmt
    - rustup default master
    - set PATH=%PATH%;C:\Users\appveyor\.rustup\toolchains\master\bin
    - rustc -V
    - cargo -V

build: false

test_script:
    - set RUST_BACKTRACE=1
    - cargo build --features debugging
    - cargo test --features debugging

notifications:
    - provider: Email
      on_build_success: false
