environment:
    global:
        PROJECT_NAME: rust-clippy
    matrix:
        - TARGET: i686-pc-windows-gnu
          MSYS2_BITS=32
        - TARGET: i686-pc-windows-msvc
          MSYS2_BITS=32
        - TARGET: x86_64-pc-windows-gnu
          MSYS2_BITS=64
        - TARGET: x86_64-pc-windows-msvc
          MSYS2_BITS=64

install:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - rustup-init.exe -y --default-host %TARGET% --default-toolchain nightly
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
    - rustc -V
    - cargo -V

build: false

test_script:
    - cargo build --features debugging
    - cargo test --features debugging
    - mkdir -p rust/cargo/bin
    - copy target/debug/cargo-clippy rust/cargo/bin/cargo-clippy
    - PATH=%PATH%;rust/cargo/bin cargo clippy -- -D clippy
    - cd clippy_lints && PATH=%PATH%;../rust/cargo/bin cargo clippy -- -D clippy && cd ..

notifications:
    - provider: Email
      on_build_success: false
