cargo-features = ["profile-overrides"]

[package]
name = "rustc_codegen_cranelift"
version = "0.1.0"
authors = ["bjorn3 <bjorn3@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
# These have to be in sync with each other
cranelift = { git = "https://github.com/CraneStation/cranelift.git" }
cranelift-module = { git = "https://github.com/CraneStation/cranelift.git" }
cranelift-faerie = { git = "https://github.com/CraneStation/cranelift.git" }
target-lexicon = "0.8.1"
faerie = "0.11.0"

#goblin = "0.0.17"
ar = "0.8.0"
bitflags = "1.1.0"
byteorder = "1.2.7"
libc = "0.2.53"
tempfile = "3.0.7"
gimli = { git = "https://github.com/gimli-rs/gimli.git" }
indexmap = "1.0.2"
object = "0.12.0"
libloading = "0.5.1"

# Uncomment to use local checkout of cranelift
#[patch."https://github.com/CraneStation/cranelift.git"]
#cranelift = { path = "../cranelift/cranelift-umbrella" }
#cranelift-module = { path = "../cranelift/cranelift-module" }
#cranelift-simplejit = { path = "../cranelift/cranelift-simplejit" }
#cranelift-faerie = { path = "../cranelift/cranelift-faerie" }

#[patch."https://github.com/gimli-rs/gimli.git"]
#gimli = { path = "../" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cranelift-simplejit = { git = "https://github.com/CraneStation/cranelift.git" }

[patch.crates-io]
object = { git = "https://github.com/gimli-rs/object.git" }

[profile.dev.overrides."*"]
opt-level = 3
