[package]
name = "rustc_codegen_cranelift"
version = "0.1.0"
authors = ["bjorn3 <bjorn3@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
#cranelift = "0.14.0"
#cranelift-module = "0.14.0"
#cranelift-simplejit = "0.14.0"
#cranelift-faerie = "0.14.0"

cranelift = { git = "https://github.com/CraneStation/cranelift.git" }
cranelift-module = { git = "https://github.com/CraneStation/cranelift.git" }
cranelift-simplejit = { git = "https://github.com/CraneStation/cranelift.git" }
cranelift-faerie = { git = "https://github.com/CraneStation/cranelift.git" }
target-lexicon = "0.0.3"
#goblin = "0.0.17"
faerie = "0.5.0"
ar = "0.6.0"
bitflags = "1.0.3"
byteorder = "1.2.6"

# Uncomment to use local checkout of cranelift
#[patch."https://github.com/CraneStation/cranelift.git"]
#cranelift = { path = "../cranelift/lib/umbrella" }
#cranelift-module = { path = "../cranelift/lib/module" }
#cranelift-simplejit = { path = "../cranelift/lib/simplejit" }
#cranelift-faerie = { path = "../cranelift/lib/faerie" }