[package]
name = "rustc_codegen_cranelift"
version = "0.1.0"
authors = ["bjorn3 <bjorn3@users.noreply.github.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
cranelift = "0.14.0"
cranelift-module = "0.14.0"
cranelift-simplejit = "0.14.0"
#cranelift-faerie = "0.14.0"
