[package]
name = "clippy"
version = "0.0.68"
authors = [
	"Manish Goregaokar <manishsmail@gmail.com>",
	"Andre Bogus <bogusandre@gmail.com>",
	"Georg Brandl <georg@python.org>",
	"Martin Carton <cartonmartin@gmail.com>"
]
description = "A bunch of helpful lints to avoid common pitfalls in Rust"
repository = "https://github.com/Manishearth/rust-clippy"
readme = "README.md"
license = "MPL-2.0"
keywords = ["clippy", "lint", "plugin"]

[lib]
name = "clippy"
plugin = true
test = false

[[bin]]
name = "cargo-clippy"
path = "src/lib.rs"
test = false

[dependencies]
regex-syntax = "0.3.0"
regex_macros = { version = "0.1.33", optional = true }
semver = "0.2.1"
toml = "0.1"
unicode-normalization = "0.1"
quine-mc_cluskey = "0.2.2"

[dev-dependencies]
compiletest_rs = "0.1.0"
lazy_static = "0.1.15"
regex = "0.1.56"
rustc-serialize = "0.3"

[features]
debugging = []
test-regex_macros = ["regex_macros"]
