[package]
authors = ["bjorn3 <bjorn3@users.noreply.github.com>"]
name = "sysroot"
version = "0.0.0"

[dependencies]
core = { path = "./sysroot_src/src/libcore" }
compiler_builtins = "0.1"
alloc = { path = "./sysroot_src/src/liballoc" }
std = { path = "./sysroot_src/src/libstd", features = ["panic_unwind"] }

alloc_system = { path = "./alloc_system" }

[patch.crates-io]
rustc-std-workspace-core = { path = "./sysroot_src/src/tools/rustc-std-workspace-core" }
rustc-std-workspace-alloc = { path = "./rustc-std-workspace-alloc" }

[profile.dev]
# FIXME On macOS statics and promoted constants have the wrong alignment. This causes a debug
# assertion in `copy_nonoverlapping` to panic.
debug-assertions = false

[profile.release]
debug = true
debug-assertions = false
