[package]
authors = ["The Rust Project Developers"]
name = "rustc_trans_traits"
version = "0.0.0"

[lib]
name = "rustc_trans_traits"
path = "lib.rs"
crate-type = ["dylib"]
test = false

[dependencies]
owning_ref = "0.3.3"

rustc = { path = "../librustc" }
rustc_back = { path = "../librustc_back" }
rustc_incremental = { path = "../librustc_incremental" }
