blank_issues_enabled: true
contact_links:
  - name: Rust Programming Language Forum
    url: https://users.rust-lang.org
    about: Please ask and answer questions about Rust here.
  - name: Rust Internals Forum
    url: https://internals.rust-lang.org/
    about: Please discuss language feature requests here.
