[package]
authors = ["The Rust Project Developers"]
name = "rustc_lang_items"
version = "0.0.0"
edition = "2018"

[lib]
name = "rustc_lang_items"
path = "lib.rs"

[dependencies]
lazy_static = "1"
rustc_data_structures = { path = "../librustc_data_structures" }
rustc_hir = { path = "../librustc_hir" }
rustc_macros = { path = "../librustc_macros" }
rustc_serialize = { path = "../libserialize", package = "serialize" }
rustc_span = { path = "../librustc_span" }
syntax = { path = "../libsyntax" }
