[package]
authors = ["The Rust Project Developers"]
name = "rustc_lint"
version = "0.0.0"

[lib]
name = "rustc_lint"
path = "lib.rs"
crate-types = ["rlib", "dylib"]
test = false

[dependencies]
log = "0.3"
rustc = { path = "../librustc" }
rustc_const_eval = { path = "../librustc_const_eval" }
syntax = { path = "../libsyntax" }
syntax_pos = { path = "../libsyntax_pos" }
lazy_static = "1.0"
regex = "0.2.3"
