[package]
authors = ["The Rust Project Developers"]
name = "rustc_trans_utils"
version = "0.0.0"

[lib]
name = "rustc_trans_utils"
path = "lib.rs"
crate-type = ["dylib"]
test = false

[dependencies]
log = "0.3"
rustc = { path = "../librustc" }
rustc_incremental = { path = "../librustc_incremental" }
syntax = { path = "../libsyntax" }
syntax_pos = { path = "../libsyntax_pos" }
