[package]
authors = ["The Rust Project Developers"]
name = "rustc_target"
version = "0.0.0"

[lib]
name = "rustc_target"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
syntax = { path = "../libsyntax" }
serialize = { path = "../libserialize" }
log = "0.4"
rand = "0.4"

[features]
jemalloc = []
