[package]
name = "compiler_builtins"
# Make sure the `compiler_builtins` from crates.io doesn't take precedence over this
# replacement by specifying a higher version than the one on crates.io.
version = "0.1.100"
authors = ["bjorn3 <bjorn3@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "compiler_builtins"
path = "lib.rs"
test = false
doc = false

[dependencies]
core = { path = "../sysroot_src/src/libcore" }

[features]
rustc-dep-of-std = []
c = []
