steps:

# Note that this is originally from the github releases patch of Ninja
- bash: |
    set -e
    mkdir ninja
    curl -o ninja.zip https://rust-lang-ci-mirrors.s3-us-west-1.amazonaws.com/rustc/2017-03-15-ninja-win.zip
    7z x -oninja ninja.zip
    rm ninja.zip
    echo "##vso[task.setvariable variable=RUST_CONFIGURE_ARGS]$RUST_CONFIGURE_ARGS --enable-ninja"
    echo "##vso[task.prependpath]`pwd`/ninja"
  displayName: Download and install ninja
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
