[workspace]
members = [
  "bootstrap",
  "rustc",
  "libstd",
  "libtest",
  "tools/cargotest",
  "tools/compiletest",
  "tools/error_index_generator",
  "tools/linkchecker",
  "tools/rustbook",
  "tools/tidy",
  "tools/build-manifest",
  "tools/remote-test-client",
  "tools/remote-test-server",
]

# These projects have their own Cargo.lock
exclude = [
  "tools/cargo",
  "tools/rls",
]

# These options are controlled from our rustc wrapper script, so turn them off
# here and have them controlled elsewhere.
[profile.dev]
debug = false
debug-assertions = false
[profile.test]
debug = false
debug-assertions = false
