name: Remark

on:
  push:
    paths:
    - '**.md'
  pull_request:
    paths:
    - '**.md'

jobs:
  remark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
    - name: Install remark
      run: npm install remark-cli remark-lint remark-lint-maximum-line-length remark-preset-lint-recommended

    - name: Check *.md files
      run: git ls-files -z '*.md' | xargs -0 -n 1 -I {} ./node_modules/.bin/remark {} -u lint -f > /dev/null
